/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "rbjyragopwwuyfbnjoqk"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJianlyYWdvcHd3dXlmYm5qb3FrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxNzQxNjIsImV4cCI6MjA3Nzc1MDE2Mn0.3o-YqokIkHM1XDgc55gteU2ueciS0DOhXnxKkA-38aU"